Fixed declaration of FlexContainerType
line/line-bot-sdk-go pull request #180
Opened 2019-11-15 08:42 UTC by Nazozen

type FlexContainerType = string // alias type

Removed "=" in this declaration.

If this "=" is present, the linebot definition hover message will not be displayed in VSC on Mac OS.

Example
test.go code.

func testProc () {
var x linebot.TemplateAction
x.TemplateAction ()
_ = linebot.Client {}
_ = linebot.TextMessage {}
}

At this time, even if the mouse cursor is hovered over TemplateAction, Client, TextMessage, etc., the hint message is not displayed.

type FlexContainerType = string // alias type

This "=" is grammatical, but the VSC Go plugin doesn't seem to interpret correctly.

2019-11-16 01:47 UTC, oklahomer requested changes
Thank you for the fix. I didn't notice until this p-r.
Could you also remove the associated comment of "// alias type" for us? The previous declaration of `type FlexContainerType = string` was actually a [type alias](https://talks.golang.org/2016/refactor.article#TOC_5.3.) hence the comment was correct, but now it is a simple type definition so the comment is misleading.

2019-11-16 23:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/line/line-bot-sdk-go?pullRequest=180) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/line/line-bot-sdk-go?pullRequest=180) before we can accept your contribution.<br/><hr/>**makoto** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/line/line-bot-sdk-go?pullRequest=180) it.</sub>

2019-11-17 01:09 UTC, Nazozen commented
Thank you for reply.

Okay, this is not a comment I added, but delete it.


> 2019/11/16 10:47、Go Hagiwara <notifications@github.com>のメール:
> 
> @oklahomer requested changes on this pull request.
> 
> Thank you for the fix. I didn't notice until this p-r.
> Could you also remove the associated comment of "// alias type" for us? The previous declaration of type FlexContainerType = string was actually a type alias hence the comment was correct, but now it is a simple type definition so the comment is misleading.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

2019-11-17 01:25 UTC, oklahomer reviewed
@Nazozen Thank you for those changes. LGTM 🎉 
However, before merging this, could you sign CLA as mentioned at https://github.com/line/line-bot-sdk-go/pull/180#issuecomment-554685612 ?

2019-11-17 01:51 UTC, Nazozen commented
Excuse me.

I signed it, what else should I do?
I'm not used to using Github.


> 2019/11/17 10:25、Go Hagiwara <notifications@github.com>のメール:
> 
> @oklahomer commented on this pull request.
> 
> @Nazozen Thank you for those changes. LGTM 🎉
> However, before merging this, could you sign CLA as mentioned at #180 (comment) ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

2019-11-17 03:03 UTC, oklahomer commented
[This instruction on account setting](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user) might help you. When you take a look at the commit logs, you'll find the email address and account name differ from your Github account.
By running `git config user.email`, `git config user.name` and then properly fixing the previous commit logs should fix the issue.

2019-11-17 05:46 UTC, Nazozen commented
I've fixed it. Please checkout.

2019-11-17 08:10 UTC, oklahomer commented
Take a look at https://github.com/line/line-bot-sdk-go/pull/180#issuecomment-554685612 and you'll find two names listed: Nazozen and makoto. Nazozen is listed since later commits are done after proper configuration for Nazozen. However previous commits still belong to makoto, which does not have the proper configuration. That is why I said below:
> and then properly fixing the previous commit logs should fix the issue

If you are not sure how to do this, you can just close this p-r, re-create a new branch from `master` again and apply the same change. This time, your git configuration is already tied to the proper account.

2019-11-17 12:50 UTC, closed without merging

2019-11-17 13:02 UTC, Nazozen commented
I’m so sorry.

I’ve closed previous p-r and create new pull request.

Please check out.

Thank you.

> 2019/11/17 17:10、Go Hagiwara <notifications@github.com>のメール:
> 
> Take a look at #180 (comment) and you'll find two names listed: Nazozen and makoto. Nazozen is listed since later commits are done after proper configuration for Nazozen. However previous commits still belong to makoto, which does not have the proper configuration. That is why I said below:
> 
> and then properly fixing the previous commit logs should fix the issue
> 
> If you are not sure how to do this, you can just close this p-r, re-create a new branch from master again and apply the same change. This time, your git configuration is already tied to the proper account.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>