refactored error comparison to use errors.Is
line/line-bot-sdk-go pull request #427
Opened 2024-02-18 12:26 UTC by Ebi-web

## Background
We ran the main function of the echo bot included in the SDK in the PR author's environment. I then threw an HTTP request without the x-line-signature HTTP header.

In the webhook.ParseRequest function, it returns ErrInvalidSignature if the x-line-signature header is not present in the request. So the caller should originally return HTTP status code 400. However, in the author's environment, it returned 500. In other words, the error comparison that should have been true was false. The error in the webhook package is now compared to the error returned by the ParseRequest function so that it returns 400, which is what would be expected.

The author is using macOS Ventura 13.6.1, Intel Corei7, Golang 1.20.6.

## Changes
- Updated error comparison from `==` to `errors.Is` in `examples/echo_bot/server.go`.

2024-02-29 12:39 UTC, kkdai approved these changes

2024-02-29 12:39 UTC, kkdai approved these changes
LGTM

2024-02-29 13:45 UTC, Yang-33 reviewed
Ah, that's correct... Thank you for fixing this @Ebi-web !
I left minor comments but LGTM too. Please fix some errors. after that, I'll merge this change into master~

2024-02-29 13:45 UTC, Yang-33 commented on examples/echo_bot/server.go
> +			if errors.Is(err, webhook.ErrInvalidSignature) {
please import `"errors"` (CI failed)

2024-02-29 13:45 UTC, Yang-33 commented on examples/echo_bot/server.go
> +			if errors.Is(err, webhook.ErrInvalidSignature) {
and please delete unused import `"github.com/line/line-bot-sdk-go/v8/linebot"`

2024-03-04 08:36 UTC, kkdai requested changes

2024-03-04 08:37 UTC, kkdai commented on examples/echo_bot/server.go
> +			if errors.Is(err, webhook.ErrInvalidSignature) {
we don't need linebot package anymore.

2024-03-20 01:44 UTC, closed without merging